[package]
name = "rustyboi"
version = "0.1.0"
authors = ["Liam Nickell", "Justin Xie", "Tingran Wang", "Owen Guo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# Testing

[dependencies]
